version: '3.9'
services:
  echo-mongodb:
    image : mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: echo-mongodb-admin
      MONGO_INITDB_ROOT_PASSWORD: echo-mongodb-admin
    expose:
      - "27017"
    ports:
      - 27017:27017
    restart: always
    volumes:
      - echo-mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  echo-mongodb:
